### ISSUE TITLE
Unable to build. Repository brewroot is not available

### ISSUE THREAD

**Issue by carlopellegriniarchijcom** [jboss-fuse/fuse#279]
I'm unable to build the project. The error seems to spring from the unavailability of the `brewroot` repository during the build of `legacy620`:
```
[ERROR] Failed to execute goal on project legacy620: Could not resolve dependencies for project org.jboss.amq:legacy620:pom:6.2.1.redhat-107: Could not transfer artifact org.jboss.amq:jboss-a-mq:zip:6.2.0.redhat-133 from/to brewroot (http://download.eng.bos.redhat.com/brewroot/repos/jb-fuse-6.2-build/latest/maven): download.eng.bos.redhat.com: unknown error: Unknown host download.eng.bos.redhat.com....
```
Is this repository really needed in this build? 

Thanks in advance,
  CarloP.

**Comment by nelsongraca** [comment]
Well I tried removing them and the build fails because it can't find the following artifact "org.jboss.amq:jboss-a-mq:zip:6.2.0.redhat-133" so much for open-source

**Comment by janstey** [comment]
Yeah that brew repo is internal only... we had to add it because of a legal requirement to only put GA distros in the Red Hat download portal where you can click through a license.. so no public Maven repos unfortunately :-(

However, I'm not even sure its needed any more on master TBH. Was more of a legacy thing to assist migration from 6.2.0 to 6.2.1. Checking!

**Comment by nelsongraca** [comment]
Assuming I want to build from a tag, if that repo is closed how do I build it? That does seem to make the fact that it is open source completely irrelevant since I would need access to the repos, forcing me to eventually buy, that makes no sense.

**Comment by janstey** [comment]
So if you pull now, master should build without the need for that internal repo. Let me know if you run into other issues.

On the general comment about open source... Fuse is certainly open source but maybe it isn't exactly what you consider to be open source :-) We publish all sources, accept pull requests, respond to issues like this one, etc. One thing we haven't put a lot of effort/time/money into for Fuse is having a separate community from the JBoss Fuse *product*. That product term is important here because this repo is essentially *the* repo for the JBoss Fuse product, which you can buy support on from Red Hat. We don't do community releases here. We could I suppose, if we decided to invest effort/time/money into that but IMHO that effort is better served building the communities of the multitude of other upstream projects that Fuse consumes. Things like Apache Camel, Karaf, CXF, ActiveMQ, Fabric8, HawtIO, etc all have their own separate communities and do releases and such - we contribute a lot to the success of those projects. Time well spent IMHO!

**Comment by carlopellegriniarchijcom** [comment]
Well, thank you very much. 
I was really evaluating the product, but being able to build it autonomously is a big plus IMHO. 
I will try to build this new version.

**Comment by carlopellegriniarchijcom** [comment]
As the project now builds correctly, this issue may be closed.
Thank you.
